# .bash_aliases
alias :q='exit'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias aliases='vim ~/.bash_aliases'
alias auditoff='sudo service auditd stop'
alias auditon='sudo service auditd start'
alias auditquo='sudo service auditd status'
alias cdcd='cd /mnt/dvd'
alias cdmnt='sudo mount /dev/sr0 /mnt/dvd'
alias cdmntcd='cdmnt;cdcd'
alias cls='clear'
alias clusters='vim ~/.clusterssh/clusters'
alias clustesr='vim ~/.clusterssh/clusters'
alias dstamp='date +'\''%Y%m%d'\'''
alias dtstamp='date +'\''%Y%m%d%H%M%S'\'''
alias echo='echo -e'
alias egrep='egrep --color=auto'
alias eixt='exit'
alias enableUSB='if [[ -f /lib/modules/$(uname -r)/kernel/drivers/usb/storage/usb-storage.ko ]]; then insusb; else usbunxz && insusb; fi'
alias exi='exit'
alias exitt='exit'
alias exot='exit'
alias exut='exit'
alias ff='find . -name'
alias fgrep='fgrep --color=auto'
alias fixff='rm ~/.mozilla/firefox/*/{lock,.parentlock}'
alias fns='vim ~/.bash_functions'
alias fr='sudo find / -name'
alias genpw='pwgen -cny 15'
alias gist='history | grep'
alias ga='git add'
alias gs='git status'
alias grep='grep --color=auto'
alias grepi='grep -i'
alias igrep='grep -i'
alias insusb='sudo insmod /lib/modules/$(uname -r)/kernel/drivers/usb/storage/usb-storage.ko'
alias jquo='quo jira'
alias jrestart='restart jira'
alias jstart='start jira'
alias jstop='stop jira'
alias kernels='rpm -qa | grep kernel | sort'
alias khosts='vim ~/.ssh/known_hosts'
alias l='ls -CF'
alias l.='ls -d .* --color=auto'
alias la='ls -a'
alias lA='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias lsfn='declare -f'
alias lsnv='lsmod | grep nv'
alias lsnouv='lsmod | grep nouv'
alias mnt='mount | column -t'
alias mntcd='sudo mount /dev/sr0 /mnt/dvd'
alias mntusb='sudo mount /dev/sdb1 /mnt/usb'
alias nocomm='sudo egrep -v "^#"'
alias quo='sudo systemctl status'
alias reload='source ~/.bashrc'
alias remove='sudo yum remove'
alias restart='sudo systemctl restart'
alias screen='screen -x -R'
alias screne='screen -x -R'
alias shy='ssh -Y'
alias sl='ls'
alias ssh='ssh -Y'
alias start='sudo systemctl start'
alias stig='/usr/java/latest/bin/java -jar ~/Downloads/STIGViewer-2.8.jar &'
alias stop='sudo systemctl stop'
alias sucp='sudo cp'
alias sudo='sudo '
alias suln='sudo ln'
alias sumv='sudo mv'
alias vm='sudo virt-manager'
alias tstamp='date +'\''%H%M%S'\'''
alias update='sudo yum update'
alias usbmnt='sudo mount /dev/sdb1 /mnt/usb'
alias usbunxz='sudo unxz /lib/modules/$(uname -r)/kernel/drivers/usb/storage/usb-storage.ko.xz'
alias vga='lspci | igrep vga'
alias vi='vim'
alias wcl='wc -l'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias zfw='sudo firewall-cmd --permanent --add-port=10050/tcp && sudo firewall-cmd --reload'
alias zget='zabbix_get -s'
alias zquo='sudo systemctl status zabbix-agent'
alias zrestart='sudo systemctl restart zabbix-agent'
alias zstart='sudo systemctl start zabbix-agent'
alias zstop='sudo systemctl stop zabbix-agent'
